#!/bin/sh

if [ ! -f .initialized ]; then
	# Container is initialized according the environment variables
	# passed to the container to setup Phabricator.
	/usr/local/bin/setup-phabricator
fi

/usr/local/sbin/runsvdir-init
