#!/bin/sh

if [ ! -f .initialized ]; then
	# Container is initialized according the environment variables
	# passed to the container to setup Phabricator.
	/usr/local/bin/setup-phabricator
fi

/usr/sbin/sshd -f /etc/ssh-phabricator/sshd_config

/usr/local/sbin/runsvdir-init
